11

diff --git a/离线部署k3s及其他环境/test2 b/离线部署k3s及其他环境/test2
--- a/离线部署k3s及其他环境/test2
+++ b/离线部署k3s及其他环境/test2
@@ -1,60 +1,54 @@
-
 log_info() {
-    echo '[INFO] ' "$@"
+  echo '[INFO] ' "$@"
 }
 log_error() {
-    echo '[WARN] ' "$@" >&2
+  echo '[WARN] ' "$@" >&2
 }
 fatal() {
-    echo '[ERROR] ' "$@" >&2
-    exit 1
+  echo '[ERROR] ' "$@" >&2
+  exit 1
 }
-
 
 check_ip_() {
 
-    CHECK_STEP1=$(echo $1 | awk -F"." '{print NF}')
-    if [ $CHECK_STEP1 -eq 4 ] || [ $CHECK_STEP1 -eq 6 ]; then
-        CHECK_STEP2=$(echo $1 | awk -F"." '{if ($1!=0 && $NF!=0) split ($0,IPNUM,".")} END \
+  CHECK_STEP1=$(echo $1 | awk -F"." '{print NF}')
+  if [ $CHECK_STEP1 -eq 4 ] || [ $CHECK_STEP1 -eq 6 ]; then
+    CHECK_STEP2=$(echo $1 | awk -F"." '{if ($1!=0 && $NF!=0) split ($0,IPNUM,".")} END \
         { for (k in IPNUM) if (IPNUM[k]==0) print IPNUM[k]; else if (IPNUM[k]!=0 && IPNUM[k]!~/[a-z|A-Z]/ && length(IPNUM[k])<=3 &&
 IPNUM[k]<=255 && IPNUM[k]!~/^0/) print IPNUM[k]}' | wc -l)
-        if [ $CHECK_STEP2 -ne $CHECK_STEP1 ]; then
-            echo "$1不是正确合法的有效IP !"
-            exit 1
-        fi
-    else
-        echo "$1不是正确合法的有效IP !"
-        exit 1
+    if [ $CHECK_STEP2 -ne $CHECK_STEP1 ]; then
+      echo "$1不是正确合法的有效IP !"
+      exit 1
     fi
+  else
+    echo "$1不是正确合法的有效IP !"
+    exit 1
+  fi
 
 }
-
 
 ccc() {
-#需要校验的IP
-IP_ADDR=$1
+  #需要校验的IP
+  IP_ADDR=$1
 
-check_ip_ $IP_ADDR
-#获取本机IP地址列表
-machine_ips=$(ip addr | grep 'inet' | grep -v 'inet6\|127.0.0.1' | grep -v grep | awk -F '/' '{print $1}' | awk '{print $2}')
-log_info "current machine ips: ${machine_ips}"
+  check_ip_ $IP_ADDR
+  #获取本机IP地址列表
+  machine_ips=$(ip addr | grep 'inet' | grep -v 'inet6\|127.0.0.1' | grep -v grep | awk -F '/' '{print $1}' | awk '{print $2}')
+  log_info "current machine ips: ${machine_ips}"
 
+  #输入的IP与本机IP进行校验
+  ip_check=false
+  for machine_ip in ${machine_ips}; do
+    if [[ "X${machine_ip}" == "X${IP_ADDR}" ]]; then
+      ip_check=true
+    fi
+  done
 
-
-#输入的IP与本机IP进行校验
-ip_check=false
-for machine_ip in ${machine_ips}; do
-  if [[ "X${machine_ip}" == "X${IP_ADDR}" ]]; then
-    ip_check=true
+  if [[ ${ip_check} != true ]]; then
+    log_error "your input ip: ${IP_ADDR} is not the current IP address of this machine!"
+    exit 1
   fi
-done
-
-if [[ ${ip_check} != true ]]; then
-  log_error "your input ip: ${IP_ADDR} is not the current IP address of this machine!"
-  exit 1
-fi 
 
 }
-
-
-ccc 172.17.0.300
+read -erp "未找到br0网卡,请直接输入本机ip:\n" ooo
+ccc $ooo
